---
# This workflow will install Python dependencies and run tests so that
# unit tests can be run against pull requests.

name: Unit-Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'  # All markdown files in the repository
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install pytest
      - name: Test with Pytest unit tests
        run: |
          python -m pytest